on: [workflow_dispatch]

jobs:
  cli_login_version_job:
    runs-on: ubuntu-latest
    name: CLI Login Job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: CLI for Microsoft 365 Run Script
        uses: ./
        id: runscript
        with:
           CLI_MICROSOFT365_SCRIPT: m365 spo mail send --webUrl https://contoso.sharepoint.com/sites/teamsite --to 'user@contoso.onmicrosoft.com' --subject 'Deployment done' --body '<h2>CLI for Microsoft 365</h2> <p>The deployment is complete.</p> <br/> Email sent via CLI for Microsoft 365 GitHub Action.'
           CLI_VERSION: 5.7.0-beta.9e8cf99
