on: [workflow_dispatch]

jobs:
  cli_runscript_job:
    runs-on: ubuntu-latest
    name: CLI Run Script Job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Login to tenant
        uses: pnp/action-cli-login@v2.0.0
        with:
          TENANT: ${{ secrets.TENANT }}
          APP_ID: ${{ secrets.APP_ID }}
          CERTIFICATE_ENCODED: ${{ secrets.CERTIFICATE_ENCODED }}
        
      - name: CLI for Microsoft 365 Run Script
        uses: ./
        id: runscript
        with:
          CLI_MICROSOFT365_SCRIPT: m365 spo mail send --webUrl https://contoso.sharepoint.com/sites/teamsite --to 'user@contoso.onmicrosoft.com' --subject 'Deployment done' --body '<h2>CLI for Microsoft 365</h2> <p>The deployment is complete.</p> <br/> Email sent via CLI for Microsoft 365 GitHub Action.'
    